language: java

jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  
before_install:
  - cd jg-bom
  - mvn clean install
  - cd ..
  
install: 
  - mvn clean install -Pprod

after_success:
  - mvn test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
  email:
    recipients:
      - jgrades.project@gmail.com
